name: C++ CI

on:
  pull_request

jobs:
  formatting-check:
    name: Formatting check
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check line breaks
        run: |
          sudo apt-get install -y dos2unix
          pushd $GITHUB_WORKSPACE
          ci-extra/check-lines.sh
          popd
      - name: Run clang-format style check
        # TODO use clang-format from a container
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '19'
          check-path: '.'

  test:
    needs: formatting-check
    name: "Test (${{ matrix.toolchain.os }}/${{ matrix.toolchain.compiler }}, ${{ matrix.build-type }})"

    timeout-minutes: 15

    strategy:
      matrix:
        toolchain:
          - { os: Linux, compiler: GCC,   runner-label: gcc-14 }
          - { os: Linux, compiler: Clang, runner-label: clang-19 }
        build-type:
          - Release
          - Debug
          - RelWithDebInfo
          - Sanitized
          - SanitizedDebug

    runs-on: [self-hosted, ubuntu, base, "${{ matrix.toolchain.runner-label }}"]

    env:
      CT_CMAKE_PRESET: "CI-${{ matrix.toolchain.compiler }}-${{ matrix.build-type }}"
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Update tests
        run: |
          ci-extra/update-tests.sh

      - name: Build
        run: |
          ci-extra/build.sh "$CT_CMAKE_PRESET"

      - name: Run tests
        run: |
          if [[ $TESTS_UPDATED -eq 1 ]]; then
            echo -e '\e[0;33mWARNING: Running a newer version of the tests than you have pushed.\e[0m'
          fi
          ci-extra/test.sh "$CT_CMAKE_PRESET"

      - name: Run tests with valgrind
        if: ${{ matrix.build-type == 'RelWithDebInfo' }}
        run: |
          ci-extra/test-valgrind.sh "$CT_CMAKE_PRESET"

  hidden-tests:
    name: Hidden tests
    needs: test
    runs-on: [self-hosted, ubuntu]
    timeout-minutes: 15
    steps:
      - name: Request test run
        run: |
          curl -sf "http://${{ secrets.RUNNER_SERVER_ADDR }}/request_run" \
            -X POST \
            -H 'Content-Type: application/json' \
            -d '{
              "gh_token": "${{ secrets.GITHUB_TOKEN }}",
              "run_id": ${{ github.run_id }},
              "pull_request": ${{ github.event.number }}
            }'
      - name: Awaiting results
        run: |
          while true; do
            json=$(curl -sf "${{ secrets.RUNNER_SERVER_ADDR }}/poll_run" \
              -X POST \
              -H 'Content-Type: application/json' \
              -d '{"gh_token": "${{ secrets.GITHUB_TOKEN }}"}')
            if [[ $(jq '.done' <<<"$json") = true ]]; then
              break
            else
              echo "$(jq -r '.status' <<<"$json")"
              sleep 30
            fi
          done
          echo "$(jq -r '.report' <<<"$json")"
          echo "$(jq -r '.report' <<<"$json")" >> $GITHUB_STEP_SUMMARY
          if [[ $(jq '.success' <<<"$json") = false ]]; then
            exit 1
          fi
